name: TDS-Main

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build-Release:
    strategy:
      matrix:
        target_system: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.target_system }}
    env:
      BUILD_EXT_DYN: ${{ matrix.target_system == 'windows-latest' && '.dll' || '.so' }}
      LIB_NAME: 'libtds'

    steps:
      - uses: actions/checkout@v4

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Build
        shell: bash
        run: |
          mkdir build && cmake . -Bbuild -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_RELEASE_TYPE=Release && cmake --build build
          ls -R

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            mv build/Debug/${{ env.LIB_NAME }}${{ env.BUILD_EXT_DYN }} .
          else
            mv build/${{ env.BUILD_PREFIX }}${{ env.LIB_NAME }}${{ env.BUILD_EXT_DYN }} .
          fi

      - name: Make Archive
        if: runner.os != 'Windows'
        shell: bash
        run: zip -r9 tds-${{ runner.os }}.zip *.lua ${{ env.LIB_NAME }}${{ env.BUILD_EXT_DYN }}

      - name: Make Archive
        if: runner.os == 'Windows'
        shell: powershell
        run: Compress-Archive -LiteralPath '*.lua' -LiteralPath ${{ env.LIB_NAME }}${{ env.BUILD_EXT_DYN }} -DestinationPath "tds-${{ runner.os }}.zip"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Stable-CI
          files: tds-${{ runner.os }}.zip
          body: |
            CI Build for Dreamweave TDS Fork
