name: TDS-Main

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build-Release:
    strategy:
      matrix:
        target_system: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.target_system }}
    env:
      BUILD_EXT_DYN: ${{ matrix.target_system == 'windows-latest' && '.dll' || '.so' }}
      BUILD_PREFIX: ${{ matrix.target_system != 'windows-latest' && 'lib' || ''}}
      LIB_NAME: 'tds'

    steps:
      - uses: actions/checkout@v4

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Build
        run: cmake . -DCMAKE_POLICY_VERSION_MINIMUM=3.5 && cmake --build .

      - name: Make Archive
        shell: bash
        run: zip -r9 tds-${{ runner.os }}.zip *.lua ${{ env.BUILD_PREFIX }}${{ env.LIB_NAME }}${{ env.BUILD_EXT_DYN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Stable-CI
          files: tds-${{ runner.os }}.7z
          body: |
            CI Build for Dreamweave TDS Fork
